In [17]:
import numpy as np

In [18]:
from __future__ import division

In [19]:
5/2

2.5

In [21]:
my_arr = np.array([[1,2,3,4],[5,6,7,8]])

In [22]:
my_arr.shape

(2, 4)

In [23]:
my_arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [24]:
my_arr.dtype

dtype('int64')

In [27]:
my_arr2 = np.array([[1],[2],[3,4]])

In [28]:
my_arr2

array([[1], [2], [3, 4]], dtype=object)

In [30]:
my_arr*2

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16]])

In [31]:
1/my_arr

array([[ 1.        ,  0.5       ,  0.33333333,  0.25      ],
       [ 0.2       ,  0.16666667,  0.14285714,  0.125     ]])

In [32]:
my_arr**2

array([[ 1,  4,  9, 16],
       [25, 36, 49, 64]])

In [33]:
my_arr-my_arr

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])