In [18]:
import numpy as np

In [19]:
arr = np.arange(0,11)

In [20]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [21]:
arr[3]

3

In [22]:
my_slice = arr[3:5]

In [23]:
my_slice

array([3, 4])

In [24]:
my_slice[1]

4

In [25]:
my_slice[1] = 100

In [26]:
my_slice

array([  3, 100])

In [27]:
arr

array([  0,   1,   2,   3, 100,   5,   6,   7,   8,   9,  10])

In [33]:
new_arr = my_slice.copy()

In [34]:
new_arr

array([  3, 100])

In [35]:
new_arr[1] = 4

In [36]:
new_arr

array([3, 4])

In [37]:
arr

array([  0,   1,   2,   3, 100,   5,   6,   7,   8,   9,  10])

In [38]:
new_array = arr[1:6].copy()

In [39]:
new_array

array([  1,   2,   3, 100,   5])

In [40]:
arr2d = np.array([[5,10,15],[10,20,30],[15,30,45]])

In [43]:
arr2d[1,2]

30

In [44]:
arr2d

array([[ 5, 10, 15],
       [10, 20, 30],
       [15, 30, 45]])

In [46]:
arr2d[:2,1:]

array([[10, 15],
       [20, 30]])

In [47]:
arr2d[:3,1:2]

array([[10],
       [20],
       [30]])

In [51]:
narr = np.zeros((10,10))

In [52]:
narr

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [58]:
len = narr.shape[1]

In [60]:
for i in np.arange(len):
    narr[i] = i

In [64]:
narr

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.],
       [ 5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.],
       [ 6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.],
       [ 7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.],
       [ 8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.],
       [ 9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.]])

Fancy indexing has 2 sets of box brackets, order of indices is irrelevant

In [63]:
narr[[2,3,4]]

array([[ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.]])

In [65]:
newarr = narr[[2,3,4]].copy()

In [66]:
newarr

array([[ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.]])

In [67]:
newarr[1]

array([ 3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.])

In [68]:
newarr[1]=4

In [69]:
newarr

array([[ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.],
       [ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.]])