In [1]:
import numpy as np

In [2]:
my_list1 = [1,2,3,4,5]

In [3]:
my_array1 = np.array(my_list1)

In [4]:
my_array1

array([1, 2, 3, 4, 5])

In [5]:
my_list2 = [2,3,4,5]

In [6]:
my_lists = [my_list1, my_list2]

In [7]:
my_lists

[[1, 2, 3, 4, 5], [2, 3, 4, 5]]

In [8]:
my_arrays = np.array(my_lists)

In [9]:
my_arrays

array([[1, 2, 3, 4, 5], [2, 3, 4, 5]], dtype=object)

In [10]:
my_list3 = [2,3,4,5,6]

In [14]:
my_lists2 = [my_list1, my_list3]

In [15]:
my_arrays2 = np.array(my_lists2)

In [16]:
my_arrays2.shape

(2, 5)

In [17]:
my_arrays2.dtype

dtype('int64')

In [18]:
np.zeros(5)

array([ 0.,  0.,  0.,  0.,  0.])

In [19]:
np.ones([5,2])

array([[ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.]])

In [20]:
np.eye(5)

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [21]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [22]:
np.arange(5,20,5)

array([ 5, 10, 15])