In [1]:
import numpy as np

In [3]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np.save('myarray',arr)

In [5]:
np.load('myarray.npy')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
arr1 = np.arange(5)
arr2 = np.arange(6,11)

In [9]:
ziparray = np.savez('ziparr.npz',x = arr1, y = arr2)

In [10]:
zarr = np.load('ziparr.npz')

In [11]:
zarr['x']

array([0, 1, 2, 3, 4])

In [12]:
zarr[0]

KeyError: '0 is not a file in the archive'

In [14]:
zarr['y'][1]

7

In [18]:
np.savetxt('arr.txt',zarr['x'], delimiter=',')

In [19]:
np.loadtxt('arr.txt', delimiter=',')[0]

0.0