In [1]:
import numpy as np

In [2]:
arr = np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766])

take e power every value in the array

In [4]:
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03,   2.20264658e+04])

binary universal functions

In [8]:
A = np.random.randn(10)
A

array([-0.07813773,  0.76316738, -0.33339646, -0.62172434,  0.53120683,
        1.2550088 , -0.14658371, -1.16803482,  0.03611446,  0.52977315])

In [9]:
B = np.random.randn(10)
B

array([-0.07388889,  0.90930198,  0.1397049 , -0.952122  ,  0.15832595,
        0.23329274, -1.86570268,  1.15629252, -0.41370554,  0.30870334])

In [10]:
np.add(A,B)

array([-0.15202662,  1.67246936, -0.19369155, -1.57384634,  0.68953279,
        1.48830154, -2.01228639, -0.0117423 , -0.37759108,  0.83847649])

In [11]:
np.maximum(A,B)

array([-0.07388889,  0.90930198,  0.1397049 , -0.62172434,  0.53120683,
        1.2550088 , -0.14658371,  1.15629252,  0.03611446,  0.52977315])